tuple1 = ("One", "Two", "Three", "Four")
print(tuple1)
print(tuple1[1])
print(type(tuple1))
notTuple = ("Tu es F ou Kwa?")
print(type(notTuple))
tupleConstructor = tuple(("Const", "Ructor"))
print(type(tupleConstructor))
lista = list(tupleConstructor)
print(type(lista))